# Generated by Django 4.2.7 on 2023-11-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
