# Generated by Django 4.2.7 on 2023-11-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=6),
        ),
    ]
