# Generated by Django 4.2.7 on 2024-01-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pin_code', models.CharField(max_length=6, verbose_name='pincode')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Tamilnadu', 'TamilNadu')], max_length=50)),
                ('place', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=10, verbose_name='phone no')),
                ('alter_phone_no', models.CharField(max_length=10, verbose_name='alternate phone no')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
