# Generated by Django 4.2.7 on 2024-08-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_myuser_is_logedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='google_img',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
