# Generated by Django 4.2.7 on 2023-12-08 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVarations',
            new_name='ProductVariant',
        ),
    ]
