# Generated by Django 4.2.7 on 2023-12-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brand_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ManyToManyField(to='shop.size'),
        ),
    ]
