# Generated by Django 4.2.7 on 2023-12-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productvariant_size_productvariant_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoery',
            options={'ordering': ('-created',), 'verbose_name': 'Categoery', 'verbose_name_plural': 'Categoeries'},
        ),
        migrations.AddField(
            model_name='color',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='size',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='prdv1/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='prdv2/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='prdv3/'),
        ),
    ]
