# Generated by Django 4.2.7 on 2023-12-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_categoery_options_color_is_active_product_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='img',
        ),
    ]
