# Generated by Django 4.2.7 on 2023-12-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_brand_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categoery',
        ),
    ]
