# Generated by Django 4.2.7 on 2023-12-19 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_whishlist_alter_cartitem_options_cart_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhishList',
            new_name='WishList',
        ),
        migrations.DeleteModel(
            name='WhishListItem',
        ),
    ]
