# Generated by Django 4.2.7 on 2023-12-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_wishlistitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='whishlist',
            new_name='wishlist',
        ),
    ]
