# Generated by Django 4.2.7 on 2023-12-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_brand_slug_categoery_slug_color_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
