# Generated by Django 4.2.7 on 2023-12-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_productvariant_size_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
