# Generated by Django 4.2.7 on 2023-12-27 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productvariant_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='prdv1/')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='prdv2/')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='prdv3/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='img_3',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='img',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.productvariantimages'),
        ),
    ]
