# Generated by Django 4.2.7 on 2023-12-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productvariantimages_remove_productvariant_img_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='color',
        ),
        migrations.AddField(
            model_name='productvariantimages',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='productvariantimages',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
