# Generated by Django 4.2.7 on 2023-12-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_productvariant_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimages',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariantimages',
            name='name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
        migrations.AddField(
            model_name='productvariantimages',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
