# Generated by Django 4.2.7 on 2023-12-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_productvariant_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variand_id',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='slug',
            field=models.SlugField(max_length=400, null=True, unique=True),
        ),
    ]
