# Generated by Django 4.2.7 on 2023-12-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_remove_productvariant_name_productvariant_variand_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimages',
            name='slug',
        ),
        migrations.AddField(
            model_name='productvariantimages',
            name='img_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
