# Generated by Django 4.2.7 on 2023-12-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_remove_productvariantimages_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='variand_id',
            new_name='variant_id',
        ),
    ]
