# Generated by Django 4.2.7 on 2024-07-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_wishlistitem_product'),
        ('shop', '0038_wishlist_wishlistitem'),
    ]

    operations = [
    ]
