# Generated by Django 4.2.7 on 2024-07-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_merge_20240722_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
