# Generated by Django 4.2.7 on 2024-01-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_staus',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Placed', 'Placed'), ('Delivered', 'Delivered')], max_length=12),
        ),
    ]
