# Generated by Django 4.2.7 on 2024-01-04 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0002_rename_payment_staus_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='checkouts.order'),
        ),
    ]
