# Generated by Django 4.2.7 on 2024-01-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0004_returns'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Returns',
        ),
    ]
