# Generated by Django 4.2.7 on 2024-01-06 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_delete_returns'),
        ('checkouts', '0005_delete_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('returning_policy', models.CharField(choices=[('Refund', 'Refund'), ('Exachange', 'Exchange')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('reason', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
