# Generated by Django 4.2.7 on 2024-01-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0007_alter_returns_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('RAZOR PAY', 'RAZOR PAY Payment')], max_length=10),
        ),
    ]
