# Generated by Django 4.2.7 on 2024-01-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0008_alter_order_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='orderitems',
            name='is_checkoutable',
            field=models.BooleanField(default=True),
        ),
    ]
