# Generated by Django 4.2.7 on 2024-01-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0009_alter_order_options_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='is_checkoutable',
        ),
    ]
